# Generated by Django 4.1.5 on 2023-01-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('experience', models.TextField()),
            ],
        ),
    ]
