# Generated by Django 4.1.5 on 2023-01-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshare", "0003_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="education",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="", max_length=255),
        ),
    ]
