# Generated by Django 4.1.5 on 2023-01-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
