# Generated by Django 4.1.5 on 2023-02-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='images'),
        ),
    ]
