# Generated by Django 4.1.5 on 2023-02-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0011_remove_post_comments_joblisting_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='company',
            field=models.CharField(default='Concordia', max_length=255),
            preserve_default=False,
        ),
    ]
