# Generated by Django 4.1.5 on 2023-03-11 08:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshare', '0013_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='user2',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='user1',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('sender', 'recipient')},
        ),
    ]
