# Generated by Django 4.1.5 on 2023-03-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0013_recommendations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendations',
            old_name='receipent',
            new_name='recipient',
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
