# Generated by Django 4.1.5 on 2023-03-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0014_rename_receipent_recommendations_recipient_and_more'),
        ('workshare', '0014_rename_user2_connection_recipient_and_more'),
    ]

    operations = [
    ]
