# Generated by Django 4.1.5 on 2023-04-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0015_remove_directmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='reciever',
            field=models.TextField(default='nijaoui@test.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directmessage',
            name='reciever_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
