# Generated by Django 4.1.5 on 2023-03-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0015_merge_20230311_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Connected')], default='pending', max_length=10),
        ),
    ]
