# Generated by Django 4.1.5 on 2023-04-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0016_directmessage_reciever_directmessage_reciever_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmessage',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='directmessage',
            old_name='reciever_id',
            new_name='receiver_id',
        ),
    ]
