# Generated by Django 4.1.5 on 2023-03-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0016_alter_connection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='required_docs',
            field=models.ManyToManyField(blank=True, default=None, to='workshare.document'),
        ),
    ]
