# Generated by Django 4.1.5 on 2023-03-29 15:30

from django.db import migrations, models
import workshare.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0017_document_joblisting_required_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='deadline',
            field=models.DateTimeField(default=workshare.models.JobListing.get_deadline),
        ),
    ]
