# Generated by Django 4.1.5 on 2023-03-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0018_joblisting_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='listing_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=8),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
