# Generated by Django 4.1.5 on 2023-04-18 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshare', '0018_chat_chatmessage_remove_directmessage_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='to_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='message_to_you', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
