# Generated by Django 4.1.5 on 2023-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0019_joblisting_link_joblisting_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='employment_term',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary'), ('CONTRACT', 'Contract'), ('CASUAL', 'Casual')], default='PERMANENT', max_length=9),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary_type',
            field=models.CharField(choices=[('ANNUALLY', 'Annually'), ('HOURLY', 'Hourly'), ('FLATRATE', 'FlatRate')], default='HOURLY', max_length=8),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(choices=[('FULLTIME', 'FullTime'), ('PARTTIME', 'PartTime'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], default='FULLTIME', max_length=10),
        ),
    ]
