# Generated by Django 4.1.5 on 2023-04-04 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workshare', '0020_joblisting_employment_term_joblisting_salary_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('unread', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('COMMENT', 'Comment'), ('CONNECTION', 'Connection'), ('JOBALERT', 'Job Alert'), ('LIKE', 'Like'), ('MESSAGE', 'Message'), ('RECOMMENDATION', 'Recommendation'), ('SYSTEM', 'System')], default='SYSTEM', max_length=14)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_notifcation_set', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notifcation_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('FULLTIME', 'FullTime'), ('PARTTIME', 'PartTime'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], max_length=10, null=True)),
                ('employment_term', models.CharField(blank=True, choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary'), ('CONTRACT', 'Contract'), ('CASUAL', 'Casual')], max_length=9, null=True)),
                ('salary_type', models.CharField(blank=True, choices=[('ANNUALLY', 'Annually'), ('HOURLY', 'Hourly'), ('FLATRATE', 'FlatRate')], max_length=8, null=True)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('listing_type', models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], max_length=8, null=True)),
                ('remote', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='workshare_n_content_f68e20_idx'),
        ),
    ]
