# Generated by Django 4.1.5 on 2023-04-14 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshare', '0021_notification_jobalert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('COMMENT', 'Comment'), ('CONNECTION', 'Connection'), ('JOBALERT', 'Job Alert'), ('JOBAPPLICATION', 'Job Application'), ('LIKE', 'Like'), ('MESSAGE', 'Message'), ('RECOMMENDATION', 'Recommendation'), ('SYSTEM', 'System')], default='SYSTEM', max_length=14),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('province', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('phone', models.IntegerField(default=0)),
                ('experience', models.TextField(default='')),
                ('work', models.TextField(default='')),
                ('education', models.TextField(default='')),
                ('volunteering', models.TextField(default='')),
                ('projects', models.TextField(default='')),
                ('courses', models.TextField(default='')),
                ('awards', models.TextField(default='')),
                ('languages', models.TextField(default='')),
                ('resume', models.FileField(blank=True, upload_to='documents/')),
                ('cover_letter', models.FileField(blank=True, upload_to='documents/')),
                ('letter_of_recommendation', models.FileField(blank=True, upload_to='documents/')),
                ('portfolio', models.FileField(blank=True, upload_to='documents/')),
                ('transcript', models.FileField(blank=True, upload_to='documents/')),
                ('other_documents', models.FileField(blank=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('true', 'Applied'), ('reject', 'Inactive')], default='true', max_length=10)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshare.joblisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
