# Generated by Django 4.1.5 on 2023-04-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0023_jobreport'),
        ('workshare', '0023_remove_joblisting_comments_remove_joblisting_likes_and_more'),
    ]

    operations = [
    ]
