# Generated by Django 4.1.5 on 2023-04-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0022_alter_comment_content_remove_post_comments_and_more'),
        ('workshare', '0023_jobreport'),
    ]

    operations = [
    ]
