# Generated by Django 4.1.5 on 2023-04-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0019_chatmessage_to_user'),
        ('workshare', '0024_merge_20230419_1850'),
    ]

    operations = [
    ]
