# Generated by Django 4.1.5 on 2023-04-23 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshare', '0025_merge_20230419_2349'),
        ('workshare', '0025_merge_20230420_2129'),
    ]

    operations = [
    ]
