export const SEND_RECOMMEND_REQUEST = "SEND_RECOMMEND_REQUEST";
export const SEND_RECOMMEND_SUCCESS = "SEND_RECOMMEND_SUCCESS";
export const SEND_RECOMMEND_FAIL = "SEND_RECOMMEND_FAIL";

export const CHECK_RECOMMEND_REQUEST = "CHECK_RECOMMEND_REQUEST";
export const CHECK_RECOMMEND_SUCCESS = "CHECK_RECOMMEND_SUCCESS";
export const CHECK_RECOMMEND_FAIL = "CHECK_RECOMMEND_FAIL";

export const CANCEL_RECOMMEND_REQUEST = "CANCEL_RECOMMEND_REQUEST";
export const CANCEL_RECOMMEND_SUCCESS = "CANCEL_RECOMMEND_SUCCESS";
export const CANCEL_RECOMMEND_FAIL = "CANCEL_RECOMMEND_FAIL";
