export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const CHANGE_PASSWORD_FOR_RESET_REQUEST = "CHANGE_PASSWORD_FOR_RESET_REQUEST";
export const CHANGE_PASSWORD_FOR_RESET_SUCCESS = "CHANGE_PASSWORD_FOR_RESET_SUCCESS";
export const CHANGE_PASSWORD_FOR_RESET_FAIL = "CHANGE_PASSWORD_FOR_RESET_FAIL";

export const FORGOT_PASSWORD_EMAIL_REQUEST_REQUEST = "FORGOT_PASSWORD_EMAIL_REQUEST_REQUEST";
export const FORGOT_PASSWORD_EMAIL_REQUEST_SUCCESS = "FORGOT_PASSWORD_EMAIL_REQUEST_SUCCESS";
export const FORGOT_PASSWORD_EMAIL_REQUEST_FAIL = "FORGOT_PASSWORD_EMAIL_REQUEST_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPLOAD_DOCUMENTS_REQUEST = "UPLOAD_DOCUMENTS_REQUEST";
export const UPLOAD_DOCUMENTS_SUCCESS = "UPLOAD_DOCUMENTS_SUCCESS";
export const UPLOAD_DOCUMENTS_FAIL = "UPLOAD_DOCUMENTS_FAIL";